# Generated by Django 3.1.4 on 2021-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='logged_by',
            field=models.CharField(default=2, editable=False, max_length=30, verbose_name='Usuário que logou o filme'),
            preserve_default=False,
        ),
    ]
