# Generated by Django 3.2.9 on 2021-11-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filme_logged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
